### ISSUE TITLE
[Feature] Task Item Undo

### ISSUE THREAD

**Issue by Hansanghyeon** [hapas-io/hyupup-storybook#4]
### 📬무엇을 

Task Item에서 Undo기능을 제공

### Design

[Figma Prototype](https://www.figma.com/proto/mNpHRpjtx4gP0Py2msjw5X/Todo?node-id=258%3A600&viewport=73%2C474%2C0.4202254116535187&scaling=min-zoom)

### 🤔왜?

https://github.com/hapas-io/hyupup/issues/9#issuecomment-682436698

## Todo

- [x] 카테고리 색상가져오기
- [x] 카테고리 색상에 따라서 입력 텍스트 색상 light or dark 변경
- [x] Undo UI 생성
- [x] Completed 후에 사라지는 인터렉션
- [x] `Undo UI` review from designers

**Comment by Hansanghyeon** [comment]
@youngroklee323 

Task Item이 여러개의 카테고리를 가지는 것을 없을 예정일까?
지금대로하면 카테고리는 한가지 분류로 정하는 것이 맞을 것같다.

**Comment by youngroklee323** [comment]
@Hansanghyeon 
맞음 카데코리별 색상을 다르게 할거고, 현재 색생은 미정.
카테고리별 뭉쳐있으면 색상별로 정렬될 예정
각 카테고리사이에는 약간의 여백이 있을예정

**Comment by Hansanghyeon** [comment]
@youngroklee323 

여러가지 카테고리를 가질수 있는데 그럴 경우 그라데이션으로 나오는 거임?

- 카테고리별 색상은 다르게함
- 리스트에서 카테고리별로 분류
  - 색상으로 정렬
  - 여백으로 separate

**Comment by Hansanghyeon** [comment]
@youngroklee323 

[[Task Item UI](https://hyupup-storybook-o8lb4b5zz.vercel.app/iframe.html?id=todos-todo-list-item--undo&viewMode=story)]리뷰요청

**Comment by Hansanghyeon** [comment]
### DEV

나중에 List에서 데이터를 받아올때 각 Task Item에 `controller` 속성에 자신의 데이터를 지우는 상태값, `setState?`로 제거하는 값을 넣어서 지우는 방식으로 처리하자

그리고 `controller`에 들어갈 함수는 **딜레이후 함수실행되게 로직을 구성**해야한다.
